#pragma once

#define UM_CLOSE (WM_USER + 9572)
#define UM_STRIP_LOADED (WM_USER + 9573)
#define UM_HEIGHT_CALCED (WM_USER + 9574)
#define UM_RESULT_DLG (WM_USER + 9575)
#define UM_ANALYSIS_DLG (WM_USER + 9576)
