#pragma once

#define WM_XTAB_SELECTED			(WM_USER+5432)
#define WM_XTAB_DESELECTED			(WM_USER+5433)
#define WM_XTAB_CLOSE				(WM_USER+5434)
#define WM_XTAB_DATACHANGE			(WM_USER+5435)
#define WM_XTAB_CHANGE_TOPRGRDSP	(WM_USER+5436)
#define WM_XTAB_CHANGE_TOJOB		(WM_USER+5437)
#define WM_XTAB_CHANGE_TOJOB1		(WM_USER+5438)
#define WM_XTAB_CHANGE_TOJOB2		(WM_USER+5439)
#define WM_XTAB_CHANGE_TOCOMPLETE	(WM_USER+5440)
#define WM_XTAB_CHANGE_TOERROR		(WM_USER+5441)
#define WM_XTAB_NEW_DATAFILE		(WM_USER+5442)
#define WM_XTAB_CHANGE_TITLE		(WM_USER+5443)
